# Generated by Django 4.2 on 2023-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_additem_company_details_customer_history_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.TextField(max_length=255),
        ),
    ]
